### ISSUE TITLE
feather with multiple channels

### ISSUE THREAD

**Issue by jturne19** [astroumd/SSINGMA#2]
Feather does not work with an image with more than one channel. Gives this error: 

`Caught exception: (../../images/Images/ImageBeamSet.cc : 109) Failed AlwaysAssert chan >=0 && chan < Int(nchan()) && stokes >= 0 && stokes < Int(nstokes())`

Our first test with very large channels (model 10) failed at this same point but we thought it was because of how large the channels were but that does not seem to be the case.

Fails with 60 channels or just 2 channels. Will have to look into feather in casa documentation.

**Comment by teuben** [comment]
I had "something" working with 2 channels (i found 1 channel wasn't working for me), but then I noticed the velocity header was all messed up. So maybe use imhead() on the imsubimage version and see if that looks sane. It seems tp2vis wasn't too happy with the result. casaviewer on the dirtyimage gave crazy velocities.

**Comment by bmason72** [comment]
In the past I've seen things like this when inputs were not formatted &
co-registered to each other properly ... in particular - of seeming
relevance here - both inputs should have the same freq. axes and # of
channels as well as a stokes axis. The stokes axis may well be null, i.e.,
structural only, with a single "entry" corresponding to stokes I or pseudo
I. My hands on experience with feather is a couple years old, maybe it has
been made smarter in the meantime ... or of course maybe there is a case
that is broken and you have found an issue.

 Brian

**Comment by jturne19** [comment]
Feather can't handle having a different beam for each channel. I've updated our default tclean to use a common beam for all channels to fix this. I don't think having a common beam will change much of anything in terms of flux since the beams for each channel were essentially the same anyways.

**Comment by teuben** [comment]
Ouch Ouch, this can be a huge problem.  I've had many situations where mstransform() and/or tp2vis() data would cause the first or last channel to be blanked...  I also liked the common beam, since that simplifies the computation in programs such as immoments.  But then, if I had an alma blank out on me in one channel, the the TP data with it's big beam come in as the only one , it means that now ALL my channels got the huge TP beam!!!!!

I've read a few JIRA tickets and spoke to the mstransform person [i'll see him again next week], and will bring this up again, but he was shaking his head and said, yes, this could possibly be a problem in mstransform.

Given that we're mstransforming to an LSRK fframe, any ephemeris information is now excluded ( i think) as the possible cause of the problem, but I do see that problem come back in my regression now (i  think).
